#ifndef INTRO_HEADER_H
#define INTRO_HEADER_H

#include "types.h"

// geo
extern const GeoLayout intro_geo_0002D0[];
extern const GeoLayout intro_geo_00035C[];
extern const GeoLayout intro_geo_0003B8[];
extern const GeoLayout intro_geo_000414[];

// leveldata
extern Lights1 Logo_Material_001_f3d_lights;
extern Vtx Logo_Logo_mesh_vtx_0[1333];
extern Gfx Logo_Logo_mesh_tri_0[];
extern Gfx mat_Logo_Material_001_f3d[];
extern Gfx Logo_Logo_mesh[];
extern Lights1 titlescnree__0_f3d_lights;
extern Lights1 titlescnree__1_f3d_lights;
extern Lights1 titlescnree__2_f3d_lights;
extern Lights1 titlescnree__3_f3d_lights;
extern Lights1 titlescnree__4_f3d_lights;
extern Lights1 titlescnree__5_f3d_lights;
extern Lights1 titlescnree__6_f3d_lights;
extern Lights1 titlescnree__7_f3d_lights;
extern Lights1 titlescnree__8_f3d_lights;
extern Lights1 titlescnree__9_f3d_lights;
extern Lights1 titlescnree__10_f3d_lights;
extern Lights1 titlescnree__11_f3d_lights;
extern Lights1 titlescnree__12_f3d_lights;
extern Lights1 titlescnree__13_f3d_lights;
extern Lights1 titlescnree__14_f3d_lights;
extern Lights1 titlescnree__15_f3d_lights;
extern Lights1 titlescnree__16_f3d_lights;
extern u8 titlescnree__0_ci4[];
extern u8 titlescnree__0_ci4_pal_rgba16[];
extern u8 titlescnree__1_i8[];
extern u8 titlescnree__2_ci4[];
extern u8 titlescnree__2_ci4_pal_rgba16[];
extern u8 titlescnree__3_ci4[];
extern u8 titlescnree__3_ci4_pal_rgba16[];
extern u8 titlescnree__4_ci4[];
extern u8 titlescnree__4_ci4_pal_rgba16[];
extern u8 titlescnree__5_ci4[];
extern u8 titlescnree__5_ci4_pal_rgba16[];
extern u8 titlescnree__6_ci4[];
extern u8 titlescnree__6_ci4_pal_rgba16[];
extern u8 titlescnree__7_ci4[];
extern u8 titlescnree__7_ci4_pal_rgba16[];
extern u8 titlescnree__8_ci4[];
extern u8 titlescnree__8_ci4_pal_rgba16[];
extern u8 titlescnree__9_ci4[];
extern u8 titlescnree__9_ci4_pal_rgba16[];
extern u8 titlescnree__10_ci4[];
extern u8 titlescnree__10_ci4_pal_rgba16[];
extern u8 titlescnree__11_ci4[];
extern u8 titlescnree__11_ci4_pal_rgba16[];
extern u8 titlescnree__12_ci4[];
extern u8 titlescnree__12_ci4_pal_rgba16[];
extern u8 titlescnree__13_i8[];
extern u8 titlescnree__14_ci4[];
extern u8 titlescnree__14_ci4_pal_rgba16[];
extern u8 titlescnree__15_ci4[];
extern u8 titlescnree__15_ci4_pal_rgba16[];
extern u8 titlescnree__16_i8[];
extern Vtx titlescnree_welcomehome_mesh_vtx_0[64];
extern Gfx titlescnree_welcomehome_mesh_tri_0[];
extern Vtx titlescnree_welcomehome_mesh_vtx_1[864];
extern Gfx titlescnree_welcomehome_mesh_tri_1[];
extern Vtx titlescnree_welcomehome_mesh_vtx_2[26];
extern Gfx titlescnree_welcomehome_mesh_tri_2[];
extern Vtx titlescnree_welcomehome_mesh_vtx_3[21];
extern Gfx titlescnree_welcomehome_mesh_tri_3[];
extern Vtx titlescnree_welcomehome_mesh_vtx_4[62];
extern Gfx titlescnree_welcomehome_mesh_tri_4[];
extern Vtx titlescnree_welcomehome_mesh_vtx_5[24];
extern Gfx titlescnree_welcomehome_mesh_tri_5[];
extern Vtx titlescnree_welcomehome_mesh_vtx_6[25];
extern Gfx titlescnree_welcomehome_mesh_tri_6[];
extern Vtx titlescnree_welcomehome_mesh_vtx_7[69];
extern Gfx titlescnree_welcomehome_mesh_tri_7[];
extern Vtx titlescnree_welcomehome_mesh_vtx_8[67];
extern Gfx titlescnree_welcomehome_mesh_tri_8[];
extern Vtx titlescnree_welcomehome_mesh_vtx_9[101];
extern Gfx titlescnree_welcomehome_mesh_tri_9[];
extern Vtx titlescnree_welcomehome_mesh_vtx_10[14];
extern Gfx titlescnree_welcomehome_mesh_tri_10[];
extern Vtx titlescnree_welcomehome_mesh_vtx_11[7];
extern Gfx titlescnree_welcomehome_mesh_tri_11[];
extern Vtx titlescnree_welcomehome_mesh_vtx_12[46];
extern Gfx titlescnree_welcomehome_mesh_tri_12[];
extern Vtx titlescnree_welcomehome_mesh_vtx_13[26];
extern Gfx titlescnree_welcomehome_mesh_tri_13[];
extern Vtx titlescnree_welcomehome_mesh_vtx_14[56];
extern Gfx titlescnree_welcomehome_mesh_tri_14[];
extern Vtx titlescnree_welcomehome_mesh_vtx_15[123];
extern Gfx titlescnree_welcomehome_mesh_tri_15[];
extern Vtx titlescnree_welcomehome_mesh_vtx_16[71];
extern Gfx titlescnree_welcomehome_mesh_tri_16[];
extern Gfx mat_titlescnree__0_f3d[];
extern Gfx mat_revert_titlescnree__0_f3d[];
extern Gfx mat_titlescnree__1_f3d[];
extern Gfx mat_titlescnree__2_f3d[];
extern Gfx mat_revert_titlescnree__2_f3d[];
extern Gfx mat_titlescnree__3_f3d[];
extern Gfx mat_revert_titlescnree__3_f3d[];
extern Gfx mat_titlescnree__4_f3d[];
extern Gfx mat_revert_titlescnree__4_f3d[];
extern Gfx mat_titlescnree__5_f3d[];
extern Gfx mat_revert_titlescnree__5_f3d[];
extern Gfx mat_titlescnree__6_f3d[];
extern Gfx mat_revert_titlescnree__6_f3d[];
extern Gfx mat_titlescnree__7_f3d[];
extern Gfx mat_revert_titlescnree__7_f3d[];
extern Gfx mat_titlescnree__8_f3d[];
extern Gfx mat_revert_titlescnree__8_f3d[];
extern Gfx mat_titlescnree__9_f3d[];
extern Gfx mat_revert_titlescnree__9_f3d[];
extern Gfx mat_titlescnree__10_f3d[];
extern Gfx mat_revert_titlescnree__10_f3d[];
extern Gfx mat_titlescnree__11_f3d[];
extern Gfx mat_revert_titlescnree__11_f3d[];
extern Gfx mat_titlescnree__12_f3d[];
extern Gfx mat_revert_titlescnree__12_f3d[];
extern Gfx mat_titlescnree__13_f3d[];
extern Gfx mat_titlescnree__14_f3d[];
extern Gfx mat_revert_titlescnree__14_f3d[];
extern Gfx mat_titlescnree__15_f3d[];
extern Gfx mat_revert_titlescnree__15_f3d[];
extern Gfx mat_titlescnree__16_f3d[];
extern Gfx titlescnree_welcomehome_mesh[];
extern const Gfx intro_seg7_dl_0700B3A0[];
extern const Gfx intro_seg7_dl_0700C6A0[];
extern const f32 intro_seg7_table_0700C790[];
extern const f32 intro_seg7_table_0700C880[];

// script
extern const LevelScript level_intro_entry_1[];
extern const LevelScript level_intro_entry_2[];
extern const LevelScript level_intro_entry_3[];
extern const LevelScript level_intro_entry_4[];
extern const LevelScript script_intro_L1[];
extern const LevelScript script_intro_L2[];
extern const LevelScript script_intro_L3[];
extern const LevelScript script_intro_L4[];
extern const LevelScript script_intro_L5[];

#endif
