#ifndef SSL_HEADER_H
#define SSL_HEADER_H

#include "types.h"
#include "game/moving_texture.h"

// geo
extern const GeoLayout ssl_geo_0005C0[];
extern const GeoLayout ssl_geo_0005D8[];
extern const GeoLayout ssl_geo_000618[];
extern const GeoLayout ssl_geo_000630[];
extern const GeoLayout ssl_geo_000648[];
extern const GeoLayout ssl_geo_000734[];
extern const GeoLayout ssl_geo_000764[];
extern const GeoLayout ssl_geo_000794[];
extern const GeoLayout ssl_geo_0007AC[];
extern const GeoLayout ssl_geo_0007CC[];
extern const GeoLayout ssl_geo_00088C[];

// leveldata
extern const GeoLayout pyramid2_area_1_geo[];
extern const GeoLayout pyramid2_area_1[];
extern const Collision pyramid2_area_1_collision[];
extern const MacroObject pyramid2_area_1_macro_objs[];
extern Lights1 pyramid2_dl_material_4_f3d_lights;
extern Lights1 pyramid2_dl_material_3_f3d_lights;
extern u8 pyramid2_dl_material_4_ci8[];
extern u8 pyramid2_dl_material_4_ci8_pal_rgba16[];
extern u8 pyramid2_dl_material_3_ci8[];
extern u8 pyramid2_dl_material_3_ci8_pal_rgba16[];
extern Vtx pyramid2_dl_instance_0_mesh_layer_1_vtx_0[12];
extern Gfx pyramid2_dl_instance_0_mesh_layer_1_tri_0[];
extern Vtx pyramid2_dl_instance_0_001_mesh_layer_1_vtx_0[20];
extern Gfx pyramid2_dl_instance_0_001_mesh_layer_1_tri_0[];
extern Gfx mat_pyramid2_dl_material_4_f3d[];
extern Gfx mat_revert_pyramid2_dl_material_4_f3d[];
extern Gfx mat_pyramid2_dl_material_3_f3d[];
extern Gfx mat_revert_pyramid2_dl_material_3_f3d[];
extern Gfx pyramid2_dl_instance_0_mesh_layer_1[];
extern Gfx pyramid2_dl_instance_0_001_mesh_layer_1[];
extern Gfx pyramid2_dl_material_revert_render_settings[];

extern const GeoLayout pyramidlol_area_1_geo[];
extern const GeoLayout pyramidlol_area_1[];
extern const Collision pyramidlol_area_1_collision[];
extern const MacroObject pyramidlol_area_1_macro_objs[];
extern Lights1 pyramidlol_dl_material_4_f3d_lights;
extern Lights1 pyramidlol_dl_material_3_f3d_lights;
extern u8 pyramidlol_dl_material_4_ci8[];
extern u8 pyramidlol_dl_material_4_ci8_pal_rgba16[];
extern u8 pyramidlol_dl_material_3_ci8[];
extern u8 pyramidlol_dl_material_3_ci8_pal_rgba16[];
extern Vtx pyramidlol_dl_instance_0_mesh_layer_1_vtx_0[12];
extern Gfx pyramidlol_dl_instance_0_mesh_layer_1_tri_0[];
extern Vtx pyramidlol_dl_instance_0_001_mesh_layer_1_vtx_0[16];
extern Gfx pyramidlol_dl_instance_0_001_mesh_layer_1_tri_0[];
extern Gfx mat_pyramidlol_dl_material_4_f3d[];
extern Gfx mat_revert_pyramidlol_dl_material_4_f3d[];
extern Gfx mat_pyramidlol_dl_material_3_f3d[];
extern Gfx mat_revert_pyramidlol_dl_material_3_f3d[];
extern Gfx pyramidlol_dl_instance_0_mesh_layer_1[];
extern Gfx pyramidlol_dl_instance_0_001_mesh_layer_1[];
extern Gfx pyramidlol_dl_material_revert_render_settings[];

extern const GeoLayout relcansslx_area_1_geo[];
extern const GeoLayout relcansslx_area_1[];
extern const Collision relcansslx_area_1_collision[];
extern const MacroObject relcansslx_area_1_macro_objs[];
extern Lights1 relcansslx_dl___auto__f3d_lights;
extern Lights1 relcansslx_dl___auto_2_f3d_lights;
extern Lights1 relcansslx_dl___auto_3_f3d_lights;
extern Lights1 relcansslx_dl___auto_4_f3d_lights;
extern Lights1 relcansslx_dl___auto_5_f3d_lights;
extern Lights1 relcansslx_dl___auto_6_f3d_lights;
extern Lights1 relcansslx_dl___auto_7_f3d_lights;
extern Lights1 relcansslx_dl___auto_8_f3d_lights;
extern Lights1 relcansslx_dl_material_1_f3d_lights;
extern Lights1 relcansslx_dl_material_2_f3d_lights;
extern u8 relcansslx_dl___auto__ci8[];
extern u8 relcansslx_dl___auto__ci8_pal_rgba16[];
extern u8 relcansslx_dl___auto_2_ci8[];
extern u8 relcansslx_dl___auto_2_ci8_pal_rgba16[];
extern u8 relcansslx_dl___auto_3_rgba16[];
extern u8 relcansslx_dl___auto_4_ci8[];
extern u8 relcansslx_dl___auto_4_ci8_pal_rgba16[];
extern u8 relcansslx_dl___auto_5_ci8[];
extern u8 relcansslx_dl___auto_5_ci8_pal_rgba16[];
extern u8 relcansslx_dl___auto_6_ci8[];
extern u8 relcansslx_dl___auto_6_ci8_pal_rgba16[];
extern u8 relcansslx_dl___auto_7_rgba16[];
extern u8 relcansslx_dl___auto_8_ci8[];
extern u8 relcansslx_dl___auto_8_ci8_pal_rgba16[];
extern u8 relcansslx_dl_material_1_ci8[];
extern u8 relcansslx_dl_material_1_ci8_pal_rgba16[];
extern u8 relcansslx_dl_material_2_ci8[];
extern u8 relcansslx_dl_material_2_ci8_pal_rgba16[];
extern Vtx relcansslx_dl_instance_0_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_001_mesh_layer_1_vtx_0[6];
extern Gfx relcansslx_dl_instance_0_001_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_002_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_002_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_003_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_003_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_004_mesh_layer_1_vtx_0[6];
extern Gfx relcansslx_dl_instance_0_004_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_005_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_005_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_006_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_006_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_007_mesh_layer_1_vtx_0[8];
extern Gfx relcansslx_dl_instance_0_007_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_008_mesh_layer_1_vtx_0[25];
extern Gfx relcansslx_dl_instance_0_008_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_009_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_009_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_010_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_010_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_011_mesh_layer_1_vtx_0[27];
extern Gfx relcansslx_dl_instance_0_011_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_012_mesh_layer_1_vtx_0[10];
extern Gfx relcansslx_dl_instance_0_012_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_013_mesh_layer_1_vtx_0[15];
extern Gfx relcansslx_dl_instance_0_013_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_014_mesh_layer_1_vtx_0[15];
extern Gfx relcansslx_dl_instance_0_014_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_015_mesh_layer_1_vtx_0[14];
extern Gfx relcansslx_dl_instance_0_015_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_016_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_016_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_017_mesh_layer_1_vtx_0[3];
extern Gfx relcansslx_dl_instance_0_017_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_018_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_018_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_019_mesh_layer_1_vtx_0[35];
extern Gfx relcansslx_dl_instance_0_019_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_020_mesh_layer_1_vtx_0[3];
extern Gfx relcansslx_dl_instance_0_020_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_021_mesh_layer_1_vtx_0[3];
extern Gfx relcansslx_dl_instance_0_021_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_022_mesh_layer_1_vtx_0[16];
extern Gfx relcansslx_dl_instance_0_022_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_023_mesh_layer_1_vtx_0[16];
extern Gfx relcansslx_dl_instance_0_023_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_024_mesh_layer_1_vtx_0[32];
extern Gfx relcansslx_dl_instance_0_024_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_025_mesh_layer_1_vtx_0[141];
extern Gfx relcansslx_dl_instance_0_025_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_026_mesh_layer_1_vtx_0[66];
extern Gfx relcansslx_dl_instance_0_026_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_027_mesh_layer_1_vtx_0[20];
extern Gfx relcansslx_dl_instance_0_027_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_028_mesh_layer_1_vtx_0[20];
extern Gfx relcansslx_dl_instance_0_028_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_029_mesh_layer_1_vtx_0[16];
extern Gfx relcansslx_dl_instance_0_029_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_030_mesh_layer_1_vtx_0[53];
extern Gfx relcansslx_dl_instance_0_030_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_031_mesh_layer_1_vtx_0[41];
extern Gfx relcansslx_dl_instance_0_031_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_032_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_032_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_033_mesh_layer_1_vtx_0[42];
extern Gfx relcansslx_dl_instance_0_033_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_034_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_034_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_035_mesh_layer_1_vtx_0[15];
extern Gfx relcansslx_dl_instance_0_035_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_036_mesh_layer_1_vtx_0[30];
extern Gfx relcansslx_dl_instance_0_036_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_037_mesh_layer_1_vtx_0[8];
extern Gfx relcansslx_dl_instance_0_037_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_038_mesh_layer_1_vtx_0[8];
extern Gfx relcansslx_dl_instance_0_038_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_039_mesh_layer_1_vtx_0[11];
extern Gfx relcansslx_dl_instance_0_039_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_040_mesh_layer_1_vtx_0[9];
extern Gfx relcansslx_dl_instance_0_040_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_041_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_041_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_042_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_042_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_043_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_043_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_044_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_044_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_045_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_045_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_046_mesh_layer_1_vtx_0[43];
extern Gfx relcansslx_dl_instance_0_046_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_047_mesh_layer_1_vtx_0[294];
extern Gfx relcansslx_dl_instance_0_047_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_048_mesh_layer_1_vtx_0[5];
extern Gfx relcansslx_dl_instance_0_048_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_049_mesh_layer_1_vtx_0[4];
extern Gfx relcansslx_dl_instance_0_049_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_050_mesh_layer_1_vtx_0[6];
extern Gfx relcansslx_dl_instance_0_050_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_051_mesh_layer_1_vtx_0[3];
extern Gfx relcansslx_dl_instance_0_051_mesh_layer_1_tri_0[];
extern Vtx relcansslx_dl_instance_0_052_mesh_layer_1_vtx_0[16];
extern Gfx relcansslx_dl_instance_0_052_mesh_layer_1_tri_0[];
extern Gfx mat_relcansslx_dl___auto__f3d[];
extern Gfx mat_revert_relcansslx_dl___auto__f3d[];
extern Gfx mat_relcansslx_dl___auto_2_f3d[];
extern Gfx mat_revert_relcansslx_dl___auto_2_f3d[];
extern Gfx mat_relcansslx_dl___auto_3_f3d[];
extern Gfx mat_relcansslx_dl___auto_4_f3d[];
extern Gfx mat_revert_relcansslx_dl___auto_4_f3d[];
extern Gfx mat_relcansslx_dl___auto_5_f3d[];
extern Gfx mat_revert_relcansslx_dl___auto_5_f3d[];
extern Gfx mat_relcansslx_dl___auto_6_f3d[];
extern Gfx mat_revert_relcansslx_dl___auto_6_f3d[];
extern Gfx mat_relcansslx_dl___auto_7_f3d[];
extern Gfx mat_relcansslx_dl___auto_8_f3d[];
extern Gfx mat_revert_relcansslx_dl___auto_8_f3d[];
extern Gfx mat_relcansslx_dl_material_1_f3d[];
extern Gfx mat_revert_relcansslx_dl_material_1_f3d[];
extern Gfx mat_relcansslx_dl_material_2_f3d[];
extern Gfx mat_revert_relcansslx_dl_material_2_f3d[];
extern Gfx relcansslx_dl_instance_0_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_001_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_002_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_003_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_004_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_005_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_006_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_007_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_008_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_009_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_010_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_011_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_012_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_013_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_014_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_015_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_016_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_017_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_018_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_019_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_020_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_021_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_022_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_023_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_024_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_025_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_026_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_027_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_028_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_029_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_030_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_031_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_032_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_033_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_034_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_035_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_036_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_037_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_038_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_039_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_040_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_041_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_042_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_043_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_044_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_045_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_046_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_047_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_048_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_049_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_050_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_051_mesh_layer_1[];
extern Gfx relcansslx_dl_instance_0_052_mesh_layer_1[];
extern Gfx relcansslx_dl_material_revert_render_settings[];

extern Lights1 sandsss4__0_f3d_lights;
extern u8 sandsss4__0_ci8[];
extern u8 sandsss4__0_ci8_pal_rgba16[];
extern Vtx sandsss4_aOK_mesh_vtx_0[16];
extern Gfx sandsss4_aOK_mesh_tri_0[];
extern Gfx mat_sandsss4__0_f3d[];
extern Gfx mat_revert_sandsss4__0_f3d[];
extern Gfx sandsss4_aOK_mesh[];
extern Lights1 sandsss___auto_8_f3d_lights;
extern u8 sandsss___auto_8_ci8[];
extern u8 sandsss___auto_8_ci8_pal_rgba16[];
extern Vtx sandsss_instance_0_mesh_vtx_0[3];
extern Gfx sandsss_instance_0_mesh_tri_0[];
extern Gfx mat_sandsss___auto_8_f3d[];
extern Gfx mat_revert_sandsss___auto_8_f3d[];
extern Gfx sandsss_instance_0_mesh[];
extern const u8 ssl_pyramid_sand[];
extern const u8 ssl_quicksand[];
extern const Gfx ssl_dl_quicksand_pit_begin[];
extern const Gfx ssl_dl_quicksand_pit_end[];
extern const Gfx ssl_dl_pyramid_quicksand_pit_begin[];
extern const Gfx ssl_dl_pyramid_quicksand_pit_end[];
extern Movtex ssl_movtex_tris_quicksand_pit[];
extern Movtex ssl_movtex_tris_pyramid_quicksand_pit[];
extern const Gfx ssl_dl_quicksand_pit[];
extern const Gfx ssl_dl_pyramid_quicksand_pit_static[];
extern const Gfx ssl_seg7_dl_07009F48[];
extern const Gfx ssl_seg7_dl_0700BA78[];
extern const Gfx ssl_seg7_dl_0700BC18[];
extern const Gfx ssl_seg7_dl_0700BD00[];
extern const Gfx ssl_seg7_dl_0700BF18[];
extern const Gfx ssl_seg7_dl_0700FCE0[];
extern const Collision ssl_seg7_area_1_collision[];
extern const MacroObject ssl_seg7_area_1_macro_objs[];
extern const Collision ssl_seg7_collision_pyramid_top[];
extern const Collision ssl_seg7_collision_tox_box[];
extern const struct MovtexQuadCollection ssl_movtex_puddle_water[];
extern const struct MovtexQuadCollection ssl_movtex_toxbox_quicksand_mist[];
extern const Gfx ssl_dl_quicksand_begin[];
extern const Gfx ssl_dl_quicksand_end[];
extern Movtex ssl_movtex_tris_pyramid_quicksand[];
extern const Gfx ssl_dl_pyramid_quicksand[];
extern Movtex ssl_movtex_tris_pyramid_corners_quicksand[];
extern const Gfx ssl_dl_pyramid_corners_quicksand[];
extern Movtex ssl_movtex_tris_sides_quicksand[];
extern const Gfx ssl_dl_sides_quicksand[];
extern const Gfx ssl_seg7_dl_0701EE80[];
extern const Gfx ssl_seg7_dl_0701F920[];
extern const Gfx ssl_seg7_dl_0701FCE0[];
extern const Gfx ssl_seg7_dl_07021A08[];
extern const Gfx ssl_seg7_dl_07021DE8[];
extern const Gfx ssl_seg7_dl_070220A8[];
extern const Gfx ssl_seg7_dl_070221E8[];
extern const Gfx ssl_seg7_dl_070228A8[];
extern const Gfx ssl_seg7_dl_070229E8[];
extern const Gfx ssl_seg7_dl_07022CF8[];
extern const Gfx ssl_seg7_dl_070233A8[];
extern const Gfx ssl_seg7_dl_070235C0[];
extern const Collision ssl_seg7_area_2_collision[];
extern const Collision ssl_seg7_area_3_collision[];
extern const MacroObject ssl_seg7_area_2_macro_objs[];
extern const MacroObject ssl_seg7_area_3_macro_objs[];
extern const Collision ssl_seg7_collision_grindel[];
extern const Collision ssl_seg7_collision_spindel[];
extern const Collision ssl_seg7_collision_0702808C[];
extern const Collision ssl_seg7_collision_pyramid_elevator[];
extern const Collision ssl_seg7_collision_07028274[];
extern const Collision ssl_seg7_collision_070282F8[];
extern const Collision ssl_seg7_collision_07028370[];
extern const Collision ssl_seg7_collision_070284B0[];
extern const Gfx ssl_dl_pyramid_sand_pathway_floor_begin[];
extern const Gfx ssl_dl_pyramid_sand_pathway_floor_end[];
extern const Gfx ssl_dl_pyramid_sand_pathway_begin[];
extern const Gfx ssl_dl_pyramid_sand_pathway_end[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_front[];
extern const Gfx ssl_dl_pyramid_sand_pathway_front_end[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_floor[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_side[];
extern const Gfx ssl_dl_pyramid_sand_pathway_side_end[];

// script
extern const LevelScript level_ssl_entry[];

#endif
