// 0x0E000BF8
const GeoLayout wf_geo_000BF8[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 12800, geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA(1, 0, 2000, 6000, 0, 2000, 0, geo_camera_main),
            GEO_OPEN_NODE(),
            		GEO_DISPLAY_LIST(1, wf_dl_instance_0_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_001_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_002_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_003_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_004_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_005_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_006_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_007_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_008_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_009_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_010_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_011_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_012_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_013_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_014_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_015_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_016_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_017_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_018_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_019_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_020_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_021_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_022_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_023_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_024_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_025_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_026_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_027_mesh_layer_1),
		GEO_DISPLAY_LIST(1, wf_dl_instance_0_028_mesh_layer_1),
              // GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_seg7_dl_070050C8),
               GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, wf_seg7_dl_070052B8),
               GEO_RENDER_OBJ(),
               GEO_ASM(   0, geo_movtex_pause_control),
               GEO_ASM(0x2401, geo_movtex_draw_water_regions),
               GEO_ASM(   0, geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_ASM(0, geo_cannon_circle_base),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
