extern const GeoLayout pyramidlol_area_1_geo[];
extern const GeoLayout pyramidlol_area_1[];
extern const Collision pyramidlol_area_1_collision[];
extern const MacroObject pyramidlol_area_1_macro_objs[];
extern Lights1 pyramidlol_dl_material_4_f3d_lights;
extern Lights1 pyramidlol_dl_material_3_f3d_lights;
extern u8 pyramidlol_dl_material_4_ci8[];
extern u8 pyramidlol_dl_material_4_ci8_pal_rgba16[];
extern u8 pyramidlol_dl_material_3_ci8[];
extern u8 pyramidlol_dl_material_3_ci8_pal_rgba16[];
extern Vtx pyramidlol_dl_instance_0_mesh_layer_1_vtx_0[12];
extern Gfx pyramidlol_dl_instance_0_mesh_layer_1_tri_0[];
extern Vtx pyramidlol_dl_instance_0_001_mesh_layer_1_vtx_0[16];
extern Gfx pyramidlol_dl_instance_0_001_mesh_layer_1_tri_0[];
extern Gfx mat_pyramidlol_dl_material_4_f3d[];
extern Gfx mat_revert_pyramidlol_dl_material_4_f3d[];
extern Gfx mat_pyramidlol_dl_material_3_f3d[];
extern Gfx mat_revert_pyramidlol_dl_material_3_f3d[];
extern Gfx pyramidlol_dl_instance_0_mesh_layer_1[];
extern Gfx pyramidlol_dl_instance_0_001_mesh_layer_1[];
extern Gfx pyramidlol_dl_material_revert_render_settings[];
